### ISSUE TITLE
Compatibility indicator is sometimes wrong

### ISSUE THREAD

**Issue by AlsoScratch** [HielkeMinecraft/OpenNoteBlockStudio#10]
It shows "compatible" even when one parameter makes it incompatible
![tempsnip](https://user-images.githubusercontent.com/48752273/54672819-f8237780-4b33-11e9-9934-1871207a32d6.png)

**Comment by HielkeMinecraft** [comment]
Fixed in d060f083d38195d7c5e23b48655079a7086c69ef.
