### ISSUE TITLE
Php?

### ISSUE THREAD

**Issue by NTT1906** [HielkeMinecraft/OpenNoteBlockStudio#100]
Pls
or tell me how to turn mid to nbs

**Comment by Bentroen** [comment]
Just click the 'File' tab, then open a MIDI file (.mid) in the program through either 'Open song' or 'Import from MIDI'. The program will guide you through the rest.

Keep in mind you should only create issues when you find a bug in the program, or want to suggest a feature. If you need technical support, the best place to go is our [Discord](https://discord.gg/w35BqQp).
