### ISSUE TITLE
Some notes are not playing in fast tempo

### ISSUE THREAD

**Issue by VulkanRafar** [HielkeMinecraft/OpenNoteBlockStudio#101]
When I put my song, the tempo is at 20 tps, some of notes are not playing... So I don't know why this is happened

**Comment by ShinkoNet** [comment]
I think it's just the performance of your computer. I have this issue as well when there are so many notes in the project. The program tries to keep up by skipping notes.

**Comment by Bentroen** [comment]
Question: do the notes that aren't playing glow when the marker flies past them (and you just don't hear their sound), or are they simply skipped by the marker (no glow)?

**Comment by VulkanRafar** [comment]
Oh okay, will be there an improvement for that? Because, I'm using 24 tps for a song

And, new issues happen again, when making dual stereo (which is the pan right and left at the same time) it will play incorrectly and sometimes notes went skipped. Even it's not in fast tempo

**Comment by ShinkoNet** [comment]
are you on 30fps mode or 60fps mode?

**Comment by VulkanRafar** [comment]
I'm on 60 fps mode

**Comment by ShinkoNet** [comment]
Send the NBS file so I can see if it skips on my end.

**Comment by VulkanRafar** [comment]
Already did
