### ISSUE TITLE
Not Loading Custom Instruments

### ISSUE THREAD

**Issue by JDRLGaming** [HielkeMinecraft/OpenNoteBlockStudio#103]
When loading a new song, some of the custom instruments wont load, i reload them manually like i usually do after an update but some of them do not load at all. there appears to be no consistency in the file types being used

**Comment by Bentroen** [comment]
Is this still an issue in the latest version (3.7.1)?

Make sure the sounds you want to import are in the Data/Sounds folder inside the application's directory.

**Comment by JDRLGaming** [comment]
I'm not sure, the issue stopped in the last version when I moved all my
instruments to the sounds folder. It is still working atm.
