### ISSUE TITLE
Too sensitive volume and stereo bars

### ISSUE THREAD

**Issue by Encritary** [HielkeMinecraft/OpenNoteBlockStudio#104]
**Describe the bug**
After updating to 3.7.0, the volume and the stereo bars have become too sensitive.

**To Reproduce**
1. Use these bars.

**Expected behavior**
A well-usable volume bar, not jumping from 0 to 100 when you move your mouse 1 mm forward, but like it was in 3.6.0.

**Screenshots**
![image](https://user-images.githubusercontent.com/6199266/71673088-9b7b0b80-2d99-11ea-8ca9-7d7f1abb29bb.png)

**Additional context**
If it's important, I'm using ``wine`` to launch the studio.

**Comment by Bentroen** [comment]
Thanks for reporting the issue! Indeed there's something going on with the dragging mechanic, I'll investigate soon.
