### ISSUE TITLE
Noteblock Studio crashes when using some MIDI

### ISSUE THREAD

**Issue by Vnetav** [HielkeMinecraft/OpenNoteBlockStudio#108]
Hello,

When using noteblock studio, I noticed that it crashes on some MIDI songs after reaching certain point whenever song is longer or has more instruments in it. The error represents:

> ___________________________________________
> ############################################################################################
> FATAL ERROR in
> action number 1
> of Draw Event
> for object obj_controller:
> 
> local variable e(100023, -2147483648) not set before reading it.
> at gml_Script_control_draw
> ############################################################################################
> --------------------------------------------------------------------------------------------
> stack frame is
> gml_Script_control_draw (line -1)
> gml_Object_obj_controller_Draw_0

Is there any fix to this?

Thank you

P.S. If link is needed for a song, I'll gladly post it with credits to original MIDI creator.

**Comment by Bentroen** [comment]
Thanks for your report!

Could you please provide the link to the exact MIDI file you're trying to import?

**Comment by Vnetav** [comment]
Full credits to ShinkoNet (https://www.youtube.com/channel/UCaQwEEK288ADEYnRVcEzRLw)

Download link:
[](https://drive.google.com/file/d/1IYXiHrEdlEgqC2rmncbHwOZk_S9zHR3p/view)

Error pops up at ~00:00:31.
Of course, it could have a difference on different computers. If you need me to record it, I'll gladly do that.

**Comment by ShinkoNet** [comment]
I know there's nothing wrong with my MIDI so it's definitely a bug with the program.

Have you tried to save the song after import, closed the program, then re-opened it?

**Comment by Vnetav** [comment]
> I know there's nothing wrong with my MIDI so it's definitely a bug with the program.
> 
> Have you tried to save the song after import, closed the program, then re-opened it?

I've tried that before, same thing. And as I can see, it's already been fixed by Bentroen (thank you).

**Comment by Bentroen** [comment]
I applied a fix to an issue I discovered while testing this one. As I couldn't reproduce it, I'm not sure if the changes I made will indeed fix the issue. If it persists in the next version, feel free to leave a comment and I'll take a look at it again.
