### ISSUE TITLE
Not Loading Some Custom Instruments

### ISSUE THREAD

**Issue by JDRLGaming** [HielkeMinecraft/OpenNoteBlockStudio#109]
When loading a new song, some of the custom instruments wont load, i reload them manually like i usually do after an update but some of them do not load at all. there appears to be no consistency in the file types being used

**Comment by Bentroen** [comment]
Is this still an issue in the latest version (3.7.1)?

**Comment by Bentroen** [comment]
Please don't open multiple issues about the same problem; it will not help get it solved more quickly. If you have information to add, leave a comment on the original issue instead.
