### ISSUE TITLE
Not Loading Any Custom Instruments

### ISSUE THREAD

**Issue by JDRLGaming** [HielkeMinecraft/OpenNoteBlockStudio#113]
I work with numerous custom instruments in my songs but following this update note block studio does not import any custom instruments. songs that already had custom instruments prior to the update still have the instruments but now none of my songs will import any of my instruments. 

I need this issue fixed as soon as possible please or some suggestions of solutions of what to do for now.

**Comment by Bentroen** [comment]
Could you describe the issue in more detail? 
What exactly do you mean by
> none of my songs will import any of my instruments
When you select the sound file, does it give you an error, does it not set the sound to the one you picked, or does all of that happen properly but the instruments don't play in the song? Or can you not create a custom instrument at all?

**Comment by JDRLGaming** [comment]
basically, when I go to import a custom instrument into a note block song, most of them wont load. the name gets displayed in red and no sound plays. 

https://drive.google.com/drive/u/0/folders/1etL_Lk057bBc_gwXk8S6cwAHqouEBedp here is a video to demonstrate the error

**Comment by Bentroen** [comment]
Hmm, I can't open the video for some reason. Could you verify link sharing is enabled on Google Drive?

**Comment by JDRLGaming** [comment]
done. (i think)

**Comment by JacobSC51** [comment]
It appears that the program can only open custom sounds that are in its Data\Sounds directory, otherwise it'll say the file cannot be found.

**Comment by JDRLGaming** [comment]
so do i just have to move them all to that file folder then?

**Comment by Bentroen** [comment]
Well, that is the intended behavior. The program doesn't store the full path to the sound file, only its filename, which is always relative to the 'Sounds' folder. Otherwise, how is it supposed to locate custom instruments when you share the song with someone else?

**Comment by JDRLGaming** [comment]
ok, i'll move all my custom instruments to the 'Sounds' folder and see if it works.

**Comment by JacobSC51** [comment]
Then the program should either have its own built-in file picker for this that would only let you access files and folders in that directory, or at least warn you that you need to store the custom sounds in the 'Data\Sounds' directory when trying to open files from another location with the system's file choser.

**Comment by JDRLGaming** [comment]
Hi, i just moved my sounds to the 'Sounds' directory and it worked fine. thanks for the help!

**Comment by Bentroen** [comment]
@JDRLGaming No problem! Glad you got it to work. :)

@JacobSC51 A built-in file picker would be overkill for that purpose, as its neither simple to implement, nor strictly necessary. There used to be a warning in the Instruments window, but it was temporarily removed a few versions ago, due to an issue with importing instruments from another song:
![image](https://user-images.githubusercontent.com/29354120/72689711-190d7e00-3af3-11ea-8efd-f8e30b8cf0d5.png)

I hadn't realized that it was gone, so thanks for pointing that out! It will be back in the next version of the program.
