### ISSUE TITLE
EXE installer is blocked by Windows SmartScreen

### ISSUE THREAD

**Issue by grandmoffgigi** [HielkeMinecraft/OpenNoteBlockStudio#119]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShinkoNet** [comment]
We don't sign the exe files so Windows likes to caution it. Just make the safety level lower so you can install/run it.

**Comment by grandmoffgigi** [comment]
> We don't sign the exe files so Windows likes to caution it. Just make the safety level lower so you can install/run it.

I know that, but anyone who is downloading it for the first time might be put off by it

**Comment by Bentroen** [comment]
Not much we can do about that, unfortunately. It is Windows' job to warn you about programs that could potentially harm your computer; that said, there's absolutely nothing to worry about in the program. To prevent the SmartScreen warning from appearing involves acquiring a digital signature, which could cost hundreds or even thousands of dollars.

I don't see that as much of a problem, as many pieces of software downloadable on the internet (usually made by smaller companies or a single developer) pose the same problem. Bypassing the SmartScreen window only requires you to click the text that says 'More info', then 'Run anyway'. As much as we'd like to have a fancy "trusted developer" screen popping up in blue when you open the program, unfortunately, that's not an option for us at the moment.
