### ISSUE TITLE
Option to individually change volume lf certain notes. Midi note volume imported

### ISSUE THREAD

**Issue by ThatOneJose95** [HielkeMinecraft/OpenNoteBlockStudio#120]
**Is your feature request related to a problem? Please describe.**
Some midis seem to have notes working as background noise and they sound less than vocals or other notes. I can sometimes do that by making percussionayers sound less or more, pianos the most etc but sometimes midis are organized in a way that some background notes get put in same layer as the vocals and I cant really sort them manually

**Describe the enhancement you'd like**
When importing midis, notes keep the volume of the mids notes: Quiet notes in midi come quiet in NBS

You can change a specific selection of notes' volume

**Additional context**
🤔

**Comment by Bentroen** [comment]
What you're requesting was added a while ago: MIDI import does respond to note velocity stored in the file. You just have to make sure "Import note velocity" is checked in the MIDI import window. If you can't get to work, could you send the MIDI file you're trying to import?
