### ISSUE TITLE
Some fields in the NBS format page are not marked green

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [HielkeMinecraft/OpenNoteBlockStudio#124]
I may be wrong but it appears the "documentation" on the website(https://hielkeminecraft.github.io/OpenNoteBlockStudio/nbs) isn't too hot.

For example, theses are new to the new NBS format, at least according to this, https://www.stuffbydavid.com/mcnbs/format
![image](https://user-images.githubusercontent.com/21975901/74188166-c0696680-4c02-11ea-8347-dea4d990a308.png)

Also this
![image](https://user-images.githubusercontent.com/21975901/74188226-e42cac80-4c02-11ea-9144-552888f82e37.png)

But they are not marked in green, luckily I was able to figure what I was doing wrong by comparing from the stuffbydavid.com/mcnbs/format link.

It would just be cool if it could be marked in green and or show what NBS version the data was added in, as "Loop on/off" which shows green was added in version 4 if I'm not mistaken.

**Comment by THEREALWWEFAN231** [comment]
Ok well that's a bit weird, I was just looking around in the HTML code, I do see you marked Vanilla Instrument count as new version 
![image](https://user-images.githubusercontent.com/21975901/74189256-ed1e7d80-4c04-11ea-9586-3dc07712c0fa.png) but it doesn't show green, disabling background color fixes this 
![image](https://user-images.githubusercontent.com/21975901/74189342-09bab580-4c05-11ea-8214-91d1a8d3f21c.png) but messed up the rest of the tables' colors. 

But 
![image](https://user-images.githubusercontent.com/21975901/74189420-3373dc80-4c05-11ea-9e4d-b55d3a638118.png) are still not marked new version.

**Comment by Bentroen** [comment]
Yeah, I had noticed in the past that the alternating colors in the table override the green color indicating a new feature. I've been looking for a way to fix that in the CSS, but haven't managed to do it yet. I'll have another look at it soon, thanks!

**Comment by THEREALWWEFAN231** [comment]
Just saying "marking" all td "attributes" with newversion fixes the issue. I think its kind of a sloppy fix but it does work.
