### ISSUE TITLE
C8 Key Doesn't Work When Setting A Key

### ISSUE THREAD

**Issue by CreeperPookie** [HielkeMinecraft/OpenNoteBlockStudio#128]
If the C8 key is set to play on a keypress, it does not work. However, manually clicking the key or putting it in the note grid then playing will work fine.

Right Click on C8, then set it to any key.
Press that key, and it won't make the sound.

Instead of doing nothing, it should play the C8 sound from the keypress of the key that was set to it.

**Comment by Bentroen** [comment]
Confirmed.

**Comment by Bentroen** [comment]
Thanks for reporting! Fixed for next release.
