### ISSUE TITLE
Need Support NoteBlockAPI For Bukkit

### ISSUE THREAD

**Issue by 8MiYile** [HielkeMinecraft/OpenNoteBlockStudio#129]
Need Support NoteBlockAPI For Bukkit!!!!!
Because OpenNoteBlockStudio's NBS File not Support NoteBlockAPI!!

**Comment by Bentroen** [comment]
It's up to the developers of NoteBlockAPI to offer support to the newer versions of the format. This GitHub project only covers Open Note Block Studio, so issues about NoteBlockAPI must be reported [here](https://github.com/xxmicloxx/NoteBlockAPI).

Keep in mind that, while the original plugin has never been updated, there is a fork of the project that offers compatibility with all NBS versions released so far. [Here's](https://github.com/koca2000/NoteBlockAPI) a link to it.
