### ISSUE TITLE
MIDI Keyboards don't function

### ISSUE THREAD

**Issue by CubixL** [HielkeMinecraft/OpenNoteBlockStudio#130]
I try to make music on open note block studio using a midi keyboard connected via USB. I tested it on other music programs, and it worked, so I'm pretty sure ONBS is the problem.

I just plug in my keyboard and the notes don't play. Open Note Block Studio DOES say my device is connected (in the bottom right corner), and if I go over to the "MIDI device manager" setting my keyboard does show up. I thought I had to enable "record key presses" to make the notes actually play, but that doesn't actually change anything at all.

Also, what am I normally supposed to see when I press a key on my keyboard? Does the program's virtual keyboard is supposed to show that key pressed down, or just put the note into the song? Am I the only one using this feature? Is it even supposed to be possible?!

I am really confused, please help me.

**Comment by ShinkoNet** [comment]
you're normally supposed to see the virtual keyboard being pressed down at the same time. Try showing and hiding that piano from settings?

**Comment by CubixL** [comment]
nope, hasn't changed anything, although I did find a temporary solution. 
I found a program that lets me bind my MIDI keys to keyboard keys, and since you can change the selected note using a normal keyboard, I could assign it to my piano (example, C4 is R, so set R to C4 on MIDI piano and so on).

It would still be cool if you fixed this though, as other people would have a lot less harder time trying to figure out how MIDI works in open note block studio.

**Comment by CubixL** [comment]
update: it just decided to work, i have no idea what happened
however, when you play the note, the note registers about half a second later, which means everything note is delayed by one tick or so, so I guess that's another thing to fix.
I can just select the notes afterwards and put them back into their good position, but it would still be nice if it got fixed.

thanks for the help anyway!

**Comment by Bentroen** [comment]
Glad you got it to work. For whatever reason, sometimes it takes a few tries before MIDI input works as expected.

Regarding the delay, I guess that's inherent to the MIDI interface itself. (Have you noticed if it happens in any other programs that deal with MIDI devices?) The program handles the inputs as soon as it receives them, so if there's something we can even do about that, it's in the underlying MIDI library that the program uses to receive the inputs (which is a different bit of the code that we haven't delved into yet).

I'm closing this for now; feel free to leave a comment if you want to add any details.
