### ISSUE TITLE
duplicant notes when importing from midi

### ISSUE THREAD

**Issue by T0biasCZe** [HielkeMinecraft/OpenNoteBlockStudio#135]
Sometimes when importing from midi, there are duplicant notes in same column, and when they are there or not, it sound same, so when exporting, there are useless layers for duplicant notes
example this midi at column 128
[Levels_-_Avicii_Piano_Cover.mid.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/4356730/Levels_-_Avicii_Piano_Cover.mid.zip)

**Comment by Bentroen** [comment]
The program doesn't (or should not) magically add notes where there isn't one, so this is probably a consequence of two different notes in the MIDI resolving to the same note in NBS.
After inspecting the MIDI, this seems to be precisely the case: one note is C#2 and the other is C#3, but with the `Keep within octave range` option enabled, the lower one gets transposed to C#3, resulting in two identical notes. Try disabling that option and manually transposing/deleting the notes you don't want.
