### ISSUE TITLE
Macro bar will still show up even if "Show layer boxes" is turned off

### ISSUE THREAD

**Issue by P-Unintended** [HielkeMinecraft/OpenNoteBlockStudio#136]
The macro bar will show up, even though the "Show layer boxes" option is disabled.

### Steps to reproduce the behavior:
1. Go to Settings > Preferences... > Appearance, and make sure the "Show layer boxes" option is turned off.
2. Select one or more notes.
3. See the macro bar.

### Expected behavior
Obviously, I didn't expect the bar to show up.

### **Screenshot**
![image](https://user-images.githubusercontent.com/62443058/77195193-87fe5780-6ae1-11ea-87df-4faa816538b2.png)

**Comment by Bentroen** [comment]
This is _sort of_ intended. It doesn't make sense to hide the macro bar when hiding the layers, because you might still want to use it with the layers disabled. The weird appearance was simply a result of not having a better place to put it.
I'll think what can be done about that.
