### ISSUE TITLE
[Suggestion] Option to 2x TPS for more accurate MIDI import

### ISSUE THREAD

**Issue by KabanFriends** [HielkeMinecraft/OpenNoteBlockStudio#138]
When I import midis I have, sometimes some notes are in wrong tempo/skipped(overlapping) because sound notes are being snapped to the grid

like this:
![image](https://user-images.githubusercontent.com/45000995/77927196-ff9e6480-72e1-11ea-9ece-c586c4897ab1.png)
(in this example, actual MIDI has one more note between these two but there's no space to put a note there)

There should be an option to make the TPS 2x and have more space for notes so there will be less notes in wrong tempo or skipped/overlapped due to the grid snap
![image](https://user-images.githubusercontent.com/45000995/77927492-3ffde280-72e2-11ea-8ad8-115366613a0b.png)

I can manually do the same thing by making TPS 2x faster, selecting everything, expand notes and fix the skipped/wrong tempo notes but it will take time so it will be much more convenient if the software automatically did this.
I've wanted this feature for quite long so please add it in the near future version!

Some video about the problem (sorry for very low quality sound)
https://streamable.com/dkt55
(well, the second example may be the worst thing, the midi itself may be broken)
(more examples i know: the part of megalovania where 2-3 notes come at same time)

Not sure this is caused by grid snap, but making TPS 2x and having more space to put notes could make it better? (especially overlapping notes)

**Comment by Bentroen** [comment]
Implemented in c86ec53aad72778ed6aa94c58de7091edeacf6da (released in 3.8.1).
