### ISSUE TITLE
About .nbs

### ISSUE THREAD

**Issue by SamLam140330** [HielkeMinecraft/OpenNoteBlockStudio#14]
Sorry about I don't know all the function about OpenNoteBlockStudio. How to export the song to .nbs file? I just saw the datapack, mp3 and schematic only.

**Comment by Bentroen** [comment]
NBS is just the format Note Block Studio saves their files as, so to save as NBS you just pick 'Save song'.

**Comment by SamLam140330** [comment]
OK, thank you so much
