### ISSUE TITLE
Native Mac and Linux Support for OpenNBS

### ISSUE THREAD

**Issue by TechieBlort** [HielkeMinecraft/OpenNoteBlockStudio#145]
**Is your feature request related to a problem? Please describe.**
Mac and Linux Support for OpenNBS

**Describe the enhancement you'd like**
I would like native support for Mac and Linux so all Minecraft Java players can join in making songs if they choose.

**Comment by koca2000** [comment]
Duplicate of #4. According to developers it's planned but need complete rewrite.

**Comment by Bentroen** [comment]
Yep. Read this comment I sent on a similar issue for more details: https://github.com/HielkeMinecraft/OpenNoteBlockStudio/issues/132#issuecomment-608259195
