### ISSUE TITLE
Change "Room Speed" to something else

### ISSUE THREAD

**Issue by KabanFriends** [HielkeMinecraft/OpenNoteBlockStudio#146]
In preferences screen, it says "Room Speed" but I think it's weird to use here.
![image](https://user-images.githubusercontent.com/45000995/78625120-2b16e580-78c6-11ea-8535-3a10bc9d0104.png)

I think it should be changed to Frame Per Second or something better than Room Speed.
This issue/suggestion is posted just to remind the dev:
![image](https://user-images.githubusercontent.com/45000995/78625196-62859200-78c6-11ea-9456-f8025c7e46ba.png)

**Comment by cs127** [comment]
Yeah, "room speed" is weird, I guess "Room FPS" or just "FPS" would be better.

**Comment by ShinkoNet** [comment]
It's a game maker program so it makes sense technically, but for the user experience I guess it's fine to change it
