### ISSUE TITLE
FATAL ERROR when I open

### ISSUE THREAD

**Issue by ASOwnerYT** [HielkeMinecraft/OpenNoteBlockStudio#15]
I installed using the .exe installer and I checked the checkbox to open it and I get this error:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_buffer_read_string_int
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

**Comment by HielkeMinecraft** [comment]
Does this happen after updating Minecraft Note Block Studio? Or after a fresh install? A complete reinstall might fix this issue.

**Comment by HielkeMinecraft** [comment]
Looks like it's an error which happens after upgrading. I explain this in #6
