### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by Xellerate005** [HielkeMinecraft/OpenNoteBlockStudio#150]
**Describe the bug**
unable to her instrument sounds while playing/clicking piano keys

**To Reproduce**
click the piano keys or play button

**Expected behavior**
no sound from the application

**Screenshots**

**Additional context**

**Comment by ShinkoNet** [comment]
It's an issue with your computer's sound drivers. No sound output at all right? make sure your headphones/speakers are the default output device.
