### ISSUE TITLE
Move option to save file in older NBS version to a better place

### ISSUE THREAD

**Issue by LoLoAlexLoLo** [HielkeMinecraft/OpenNoteBlockStudio#151]
Let's be honest, a new datapacks from version 3.7.0 are very heavy and due to them map is loading veeery slowly.

And if I wanted to export my song in older datapack method (like in 3.6.0) - I can't do it, because older version just crashes when opening a file from new version

I can't copy notes from one app to another either

So what if we have an option to save files in older nbs versions? (Like in MS Word with .doc saving)

**Comment by Bentroen** [comment]
Go to Preferences > Save options. :)

**Comment by LoLoAlexLoLo** [comment]
Well... Okay :) Thanks!

But still, I think you should move it to "Save As"

**Comment by Bentroen** [comment]
Yeah, I'm considering moving it somewhere else, it's kinda hidden in there currently. Thanks for your feedback =)

**Comment by Bentroen** [comment]
I'll reopen this and change the title so I remember to find a better place :P
