### ISSUE TITLE
Right-clicked Key Numbers for the Mini-Keyboard

### ISSUE THREAD

**Issue by TheCraftedGamer** [HielkeMinecraft/OpenNoteBlockStudio#154]
The problem i am having is not knowing what pitch of note block I'm placing (the amount of times it would take to right-click a note block)

Its a very easy add, what would be added is an option in the settings to label the keys on the keyboard from 0-23 being how many times it would take to right-click the note block. the keys that would be labeled are those in Minecraft's 2-octave range.

![Capturejhgfhjgk](https://user-images.githubusercontent.com/65487821/82141380-85bf2d80-97f2-11ea-8e11-bc82c81b187b.PNG)
^^ This would be an example

**Comment by Bentroen** [comment]
@TheCraftedGamer I just implemented this, but I think it looks a bit clogged, especially considering the keys in the 2-octave range are the only ones that have a keyboard shortcut by default.

![image](https://user-images.githubusercontent.com/29354120/84625842-6df2cc00-aeba-11ea-9360-b2859fffbaba.png)

I'll add it anyway, but if you have any suggestions on how to improve it, please leave a comment!
