### ISSUE TITLE
Keyboard shortcuts for keys don't work when a song is playing

### ISSUE THREAD

**Issue by CreeperPookie** [HielkeMinecraft/OpenNoteBlockStudio#156]
**Describe the bug**
No matter what key you press, if the play bar is moving (the thing when you press space). However, on the piano keys, the key does get pressed down, but no sound comes out until it's paused or stopped. Also, if you click the key while it's playing it works fine; only if you use keyboard shortcuts it fails

**To Reproduce**
1. Click play or hit space bar
2. Hit a key on the piano using a keyboard shortcut

**Expected behavior**
Instead of that, the respective key sound should play.

**Comment by Bentroen** [comment]
Wow! Nice catch. Guess I never noticed this because I don't use the keyboard shortcuts very often. This should be easy to fix in the next version 👍
