### ISSUE TITLE
Is Minecraft Note Block Studio a virus?

### ISSUE THREAD

**Issue by CowLikesWheat** [HielkeMinecraft/OpenNoteBlockStudio#159]
So,
I wanted to install this program on my computer and it says the anti-virus says that it is a virus.
Since I don't want to risk it can you please verify that this program isn't a virus.

Thanks.

**Comment by Bentroen** [comment]
Of course we wouldn't distribute a virus. The only reason that your computer doesn't trust the program is that it's not digitally signed. Acquiring such licenses is very expensive, and as such not viable for independent developers like us. You can safely ignore the warnings, and if you still don't trust the program, the whole source code is available for inspection here on GitHub, so you can verify yourself if there's anything suspicious.

If you have any further questions, please let me know :)

**Comment by CowLikesWheat** [comment]
Alright then.

Thank you.
