### ISSUE TITLE
Select notes higher/lower than octave range

### ISSUE THREAD

**Issue by Heptor44** [HielkeMinecraft/OpenNoteBlockStudio#161]
**Is your feature request related to a problem? Please describe.**
I can't import most MIDIs not meant for NBS with the restriction, so I've resorted to using Double Bass and Bell for the extra 2 or so octaves. Doing this is tedious, however. 

**Describe the enhancement you'd like**
2 buttons when you right-click the track that say "Select all notes above octave limit" and "Select all notes below octave limit". They select said notes.

**Comment by Bentroen** [comment]
If you click the "Not compatible" indicator at the top, it should tell you exactly how many blocks are outside the 2 octave range and allow you to select them. The only problem is that there's no distinction between blocks that are lower and higher, so you still need to do some manual filtering.

The only workaround I can think of is to "Increase octave" until all lower notes are within range. Then, when you click "Select all notes outside the octave range" again, it will only select the higher notes. Then you can change the instrument, fix the octave, and do the same for the lower notes. You can use layer locks to filter which layers you want to select at a time.

Indeed, this is a ridiculous solution for something that should be simple to solve. I'll see if in the next version I can split that button into higher and lower notes only. :)
