### ISSUE TITLE
Unknown function when using the datapack method

### ISSUE THREAD

**Issue by NFSKG3** [HielkeMinecraft/OpenNoteBlockStudio#168]
I exported the zip to the world folder. I tried doing the command as displayed on many different versions, all said that its an unknown function. What's happening?

**Comment by Bentroen** [comment]
Is the issue related to #144? If not, please make sure the data pack is loaded properly by using `/datapack list`, and enable it with `/datapack enable <name>`.

**Comment by NFSKG3** [comment]
I haven't played Minecraft in a while and forgot how these worked.

I put it in the wrong location. Oops, my mistake.
