### ISSUE TITLE
Feature Request: Let us make the music audible for other players

### ISSUE THREAD

**Issue by dombomb64** [HielkeMinecraft/OpenNoteBlockStudio#17]
The export datapack feature is **AMAZING**. There's just one thing. Please add an option in the datapack export menu that, if checked, lets other players within a specified radius (the volume parameter in the playsound command) hear the song that you're playing as well. Y'know? Kinda like [Grandayy's AirPods video](https://youtu.be/M_tS0Wi_1N0)?

**Comment by HielkeMinecraft** [comment]
Fun idea. I'll add this.
