### ISSUE TITLE
Higher-octave cowbell sound not present in extra notes resource pack

### ISSUE THREAD

**Issue by FluxCapacitor2** [HielkeMinecraft/OpenNoteBlockStudio#171]
**Describe the bug**
There is no `minecraft:block.note_block.cow_bell_1` sound in the resource pack

**To Reproduce**
1. Apply the extra notes resource pack from https://github.com/HielkeMinecraft/OpenNoteBlockStudio/blob/master/datafiles/Data/extranotes.zip
2. Run this command ingame: `/playsound minecraft:block.note_block.cow_bell_1 record @s ~ ~ ~`
3. Notice that you don't hear a sound because it does not exist. If you were to use `/playsound minecraft:block.note_block.cow_bell record @s ~ ~ ~` you would hear the normal cowbell.

**Expected behavior**
When you run `/playsound minecraft:block.note_block.cow_bell_1 record @s ~ ~ ~` you should hear a higher-pitched cowbell, similar to all of the other notes in the resource pack

**Screenshots**
![image](https://user-images.githubusercontent.com/31071265/87593240-26c64980-c6b9-11ea-858b-78c891cd8366.png)
(notice how we see "cow_bell" and "cow_bell_-1" but no "cow_bell_1"

**Comment by MericGit** [comment]
iirc it's an issue with the sounds json. Some stuff isn't named properly

**Comment by Bentroen** [comment]
Oops, the sound event is completely missing from `sounds.json`. My bad.

**Comment by FluxCapacitor2** [comment]
I can add it real quick, I just pitched the normal one in audacity
