### ISSUE TITLE
So you know how theres no Linux support...

### ISSUE THREAD

**Issue by YEEETT** [HielkeMinecraft/OpenNoteBlockStudio#174]
#### this is not _another_ duplicate of #4 BTW
can someone recreate she sonds in [this playlist](https://www.youtube.com/playlist?list=PLVNruK5Y-WmubUJT6FM2bmhnm4BAqngo1) in nbs format? i would if i could but i use linux cuz penguins and also, u dont have 2 but just for the meme, do [this](https://www.youtube.com/watch?v=8avMLHvLwRQ) if u want

**Comment by Bentroen** [comment]
Okay. As simple as it may seem, recreating songs in NBS format is by no means a trivial thing. Depending on the length and complexity of the song, it can take from half a day to a whole _month_ to recreate a song accurately, even for someone experienced in transcribing. While you may at times find someone generous enough to do it for you, requesting song transcriptions is something we usually frown upon – even more so for whole _playlists_. This is also not the appropriate place for it, as it's meant exclusively for submitting inquiries regarding the development of the program.

As stated in the very issue you mentioned, Linux support is **coming soon** and you'll be able to transcribe those songs yourself then. Meanwhile, I kindly ask for your patience with this matter.

Please leave a comment if you have any further questions.
