### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by Inky-developer** [HielkeMinecraft/OpenNoteBlockStudio#177]
According to the readme the official discord channel can be used to get support. However, all channels are read-only (there is no discussion channel). I think that either the readme should be updated or a channel for the discord server should be added.

On a sidenode, is there a public repository of version 4.0? Or is this currently private?

**Comment by MericGit** [comment]
You have to verify by reacting in rules to gain access

**Comment by Inky-developer** [comment]
Oh. Thank you for your response.
