### ISSUE TITLE
More options for MIDI input devices

### ISSUE THREAD

**Issue by cs127** [HielkeMinecraft/OpenNoteBlockStudio#180]
**Is your feature request related to a problem? Please describe.**
The MIDI input settings are not that good. It's not even possible to disable a device. (#173)

**Describe the enhancement you'd like**
Not only I would like the ability to disable devices, but also, it would be really nice to have the ability to set different instruments for indiviual MIDI channels of each device, instead of setting instruments for the devices themselves.

**Comment by Bentroen** [comment]
Hello! Thanks for your suggestion. I just implemented an option to disable and mute individual MIDI devices.
As for your second request, sadly it's impractical at the moment. The code that _actually_ deals with receiving the MIDI messages is a very low-level bit of the program that's completely separate from the main code, and is much trickier to make changes to. Perhaps this can be taken into consideration for the v4.0 rewrite.
