### ISSUE TITLE
Removing a custom instrument while it still exists in the song causes problems

### ISSUE THREAD

**Issue by Speeder323** [HielkeMinecraft/OpenNoteBlockStudio#181]
**Describe the bug**
The program crashes if you try to select a custom instrument using the compatibility tab when the custom instrument was removed.

**To Reproduce**
1. Create a custom instrument
2. Place any amount of notes using that custom instrument
3. Remove the custom instrument
4. Go to the Minecraft Compatibility tab
5. Click on "Select affected blocks" beneath "No custom instruments must be used." text, which should be red.
6. Crash!

**Expected behavior**
When the custom instrument is removed, all notes associated with that instrument should be removed too.

**Screenshots**
![fatal error](https://user-images.githubusercontent.com/61844671/90309887-b182aa00-deec-11ea-82f9-6d3ef5e79c23.png)

**Comment by Speeder323** [comment]
Also crashes when you play the song.

**Comment by Bentroen** [comment]
Thanks for reporting! I had noticed this issue before, have yet to investigate.

**Comment by CubixL** [comment]
might not be fixed, this happened to me too today


___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

DoConv :1: illegal undefined/null use
at gml_Script_blocks_set_instruments
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_blocks_set_instruments (line -1)
gml_Script_load_song
gml_Script_draw_window_greeting
gml_Script_draw_windows
gml_Script_control_draw
gml_Object_obj_controller_Draw_0


I just loaded up a song where I recently changed the custom instruments. I didn't create/delete any, only change the .ogg they were supposed to play. The .ogg file was the same, but I renamed it to something else... I don't know what it's making it crash :P

**Comment by Bentroen** [comment]
It will be fixed on the next release. The "Resolved" tag is just to keep track of it

**Comment by CubixL** [comment]
oh okay
