### ISSUE TITLE
.nbs Magic Number

### ISSUE THREAD

**Issue by Richienb** [HielkeMinecraft/OpenNoteBlockStudio#182]
Is there a magic number encoded in the header of an nbs file that I can read to determine if a file is one. If not, what is the preferred method for doing so?

// @HielkeMinecraft

**Comment by Bentroen** [comment]
There's no header or indication that a file is in the NBS format other than the extension. You can, however, try to parse the file by reading the appropriate fields; if it fails, then you know it's most likely not a NBS file. (If it looks like a duck and quacks like a duck, then it is probably a duck).

You can find the detailed format specification on our [website](opennbs.org/format). Feel free to reply if you have any questions :)
