### ISSUE TITLE
''Extra Notes Block'' Datapack not working

### ISSUE THREAD

**Issue by Sjored778** [HielkeMinecraft/OpenNoteBlockStudio#184]
When i put the Extra Notes Block Datapack in my world and play a NB music which includes out of range note blocks, it doesn't play those out of range notes, it only plays the notes in the range.

**Comment by Bentroen** [comment]
The `Extra Note Blocks.zip` file is a **resource pack**, not a data pack, so it must go in your `.minecraft/resourcepacks` folder. Make sure to enable "Include out of range notes" when exporting the data pack, and also make sure you have the resource pack enabled when you play the song.

One last thing, keep in mind the resource pack is meant to work with **data pack playback only**; it's not possible to extend the range of the actual note blocks without using mods.

Feel free to leave a comment if you have any further questions :)

**Comment by Sjored778** [comment]
Thanks for letting me know its a Resource pack and not a Datapack! It doesn't say anywhere that it's a Resource pack (at least i didn't see it)

**Comment by Bentroen** [comment]
You're right! Maybe I should add a clear indication that it's a resource pack (it just says "pack" because otherwise it wouldn't fit on the button. :)
