### ISSUE TITLE
Crash when trying to open any MIDI (v3.3.8)

### ISSUE THREAD

**Issue by enderGuardian46** [HielkeMinecraft/OpenNoteBlockStudio#19]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

Variable obj_controller.<unknown variable>(100203, -2147483648) not set before reading it.
at gml_Script_draw_window_midi_import
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_draw_window_midi_import (line -1)
gml_Script_draw_windows
gml_Script_control_draw
gml_Object_obj_controller_Draw_0

**Comment by enderGuardian46** [comment]
Fixed after reinstalling.

**Comment by koca2000** [comment]
Duplicate of #8
