### ISSUE TITLE
all the noteblocks are by deafult the piano/harp instrument

### ISSUE THREAD

**Issue by geeblegabble** [HielkeMinecraft/OpenNoteBlockStudio#192]
**Describe the bug**
all the noteblocks are by deafult the piano/harp instrument when you load the schematic (i use worldedit it could maybe be a worldedit bug??) even if the blocks underneath are emerald,bone or something else. break/replace commands don't fix it and you have to manually break and replace the block underneath each noteblock to change the instrument

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Bentroen** [comment]
As stated in the program, schematic export is only compatible with versions up to 1.12. To remedy this problem, please create a world in 1.12, import the schematic using MCEdit or your tool of choice, rhen



The feature will be updated to work with 1.13+ in the near future.
