### ISSUE TITLE
Secret Clipboard Editor doesn't work

### ISSUE THREAD

**Issue by chenxi050402** [HielkeMinecraft/OpenNoteBlockStudio#197]
**Describe the bug**
You can't move the cursor in the secret clipboard editor.

**To Reproduce**
1. Press Ctrl+Shift+P
2. Try to move the key cursor around

**Expected behavior**
Be able to edit the clipboard.

**Comment by Bentroen** [comment]
You mean that the text doesn't appear even when you have note blocks selected? If so, it might be a bug with the text field not resetting when you open the clipboard editor.

**Comment by chenxi050402** [comment]
Fixed in 3.9.0

**Comment by chenxi050402** [comment]
It's because it resets every frame so the cursor can't be moved
