### ISSUE TITLE
File with non-latin letters will fail to open from recents docs section

### ISSUE THREAD

**Issue by LoLoAlexLoLo** [HielkeMinecraft/OpenNoteBlockStudio#2]
So yes, this is a bug from original program, and its not fixed, but if you save your nbs project with nonlatin symbols (for example i saved my file with cyrillic letters - _абв_) after restarting program it will show in recents tab like this
![image](https://user-images.githubusercontent.com/39464667/53700630-c3ae7c80-3e0d-11e9-904d-57c5bc2a8d59.png) and then fails to open 
![image](https://user-images.githubusercontent.com/39464667/53700637-dcb72d80-3e0d-11e9-8870-07071040ae38.png)

**Comment by HielkeMinecraft** [comment]
V3.3.7 adds support for cyrillic characters!
