### ISSUE TITLE
Add selection for boards

### ISSUE THREAD

**Issue by lemonztries** [HielkeMinecraft/OpenNoteBlockStudio#207]
Hello, can you add an extra board selection when exporting a map to schematic like wool?

![image](https://user-images.githubusercontent.com/71596737/96331675-d10e8e00-1067-11eb-9330-d06f9f11f387.png)

**Comment by Bentroen** [comment]
Hello! It wasn't very clear to me, what do you mean by "boards"?

The list of blocks is currently out-of-date as the schematic is intended to work only with Minecraft 1.12. If that's what you mean, then we should be updating it to 1.13+ in the near future :)
