### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Edude42** [HielkeMinecraft/OpenNoteBlockStudio#21]
**Playlists**: Allow a user to select `.nbs` files, and the program will play those in order or shuffle.
**Mass export**: Export many `.nbs` files in a playlist to `.mp3`, `.midi` (from previos request), or any other common formats.
**Mass import**: Import many `.midi` files.
**Song tabs**: A tab system to easily switch between songs.
**Dark theme**: We need this <----

These are just a bunch of suggestions I thought of.

**Comment by HielkeMinecraft** [comment]
The program is designed with 1 open song in mind, so many of these features require rewriting of the original application. Which I'm not going to do.

Dark theme seems doable though :)

**Comment by Edude42** [comment]
I understand that many of those would take a lot of rewriting and stuff. It's just a bunch of stuff I threw out. The main ones I'm wanting are the midi export and dark mode. 👍

**Comment by HielkeMinecraft** [comment]
Then I'll consider this feature request as dark theme. Please open up a separate issue for each request from now on, as it's meant to work that way.

**Comment by Edude42** [comment]
Ah alright, sorry. I'll do that next time.
