### ISSUE TITLE
ONBS Freezes with songs with two notes in the same tick

### ISSUE THREAD

**Issue by kadmuffin** [HielkeMinecraft/OpenNoteBlockStudio#213]
**Describe the bug**
Open Noteblock Studio freezes after trying to load a Song with Two Notes in the same tick.

**To Reproduce**
1. Open the provided file in the latest release of ONBS.
2. ONBS Freezes and needs to be closed forcibly.

**Expected behavior**
Throw Loading Error or Crash.

**Additional context**
The File was generated using [pynbs](https://github.com/vberlier/pynbs) with the following code:
```python
import pynbs

file = pynbs.new_file()

file.notes.extend([
    pynbs.Note(tick=0, key=33, layer=0, instrument=0),
    pynbs.Note(tick=0, key=34, layer=0, instrument=0),
    pynbs.Note(tick=1, key=35, layer=0, instrument=0)
])

file.save("sample.nbs")
```
[sample.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/5612882/sample.zip)

**Comment by Bentroen** [comment]
Well, NBS isn't supposed to know how to handle two note blocks in the same spot, so rather, this is a problem with `pynbs` generating an invalid file.

Though you probably _don't_ want two note blocks in the same spot, so I assume you forgot to change the layer of the second note to 1?

**Comment by kadmuffin** [comment]
Sincere thanks for the rapid response. That's true my fault, I will close the issue!

Sorry for the trouble.
