### ISSUE TITLE
Original song author doesn't show up if there is no song author

### ISSUE THREAD

**Issue by CubixL** [HielkeMinecraft/OpenNoteBlockStudio#214]
**Describe the bug**
In the song properties, if you leave the song author blank but type in the original song author, that author doesn't show up in the intro message when loading up the song

**To Reproduce**
1. Create/open a new song
2. Go to "Song Properties" in Settings
3. Write stuff in the Original song author field but leave Song author blank
4. Click "Song info" in Settings or load up the song again
5. The "Originally created by [person]" text doesn't show up

**Expected behavior**
The text to actually display

**Screenshots**
![song_properties](https://user-images.githubusercontent.com/61438430/101806881-7ed76f80-3ae2-11eb-86e8-afbaa3b9e9f5.PNG)
![song_info](https://user-images.githubusercontent.com/61438430/101806889-80a13300-3ae2-11eb-9bd8-4a54587d0dd6.PNG)

**Comment by Bentroen** [comment]
Fixed in c36a984c74b8922db5731899e379a694d302a3a1
