### ISSUE TITLE
No Piano Option

### ISSUE THREAD

**Issue by SirZontax** [HielkeMinecraft/OpenNoteBlockStudio#216]
Hello, 

I installed the Minecraft Note Block Studio and tried to import some midi files. 

The Problem is that I can't choose Piano as an instrument and there isn't even a piano.ogg in the Sounds folder.

Installed Version: 3.8.0 - Released 2020.07.02

**Comment by MericGit** [comment]
Piano is not a default noteblock sound included in minecraft.

You will have to add the sound file yourself and play it back with a resource pack ingame.

Perhaps you are thinking of the harp sound? That is the default noteblock sound.
