### ISSUE TITLE
Trying to export as a schematic causes a crash

### ISSUE THREAD

**Issue by cliffrabbit** [HielkeMinecraft/OpenNoteBlockStudio#220]
**Describe the bug**
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_menu:

illegal array use
at gml_Script_calculate_size
############################################################################################
gml_Script_calculate_size (line -1)
gml_Script_menu_click
gml_Script_menu_draw
gml_Object_obj_menu_Draw_0

![bug](https://user-images.githubusercontent.com/76859558/103450874-d0e56c80-4cff-11eb-9638-460ba9ac1acb.png)

I tried to reinstall and tried many things.But I could never export.
HELP ME

**Comment by Bentroen** [comment]
Confirmed.

**Comment by Aidanmikala** [comment]
I have the same issue. I have tried many things but I just cant get it fixed.

**Comment by Dykase** [comment]
I can't export it.I kept installing it over and over again, but I couldn't export it.
I hope it's resolved soon.

**Comment by MrKiddoYT** [comment]
Having the same issue over here!
