### ISSUE TITLE
Custom instruments or out of range notes' red boxes are not aligned properly

### ISSUE THREAD

**Issue by chenxi050402** [HielkeMinecraft/OpenNoteBlockStudio#221]
**Describe the bug**
The red boxes which are on all the custom instruments and out of range notes are not aligned correctly.

**To Reproduce**
1. Place a out-of-range note
2. see error

**Expected behavior**
No gaps between the note and the red line.

**Screenshots**
![image](https://user-images.githubusercontent.com/62318879/103472407-fc5e6a80-4d84-11eb-808b-57407a619d40.png)

**Comment by Bentroen** [comment]
Seems to be a bug with the `draw_rectangle` function in GMS 2.3. It seems to have become much less accurate: https://forum.yoyogames.com/index.php?threads/quick-q-draw_rectangle-not-accurate.78622/
