### ISSUE TITLE
I tried several times, but I couldn't export it. 

### ISSUE THREAD

**Issue by Dykase** [HielkeMinecraft/OpenNoteBlockStudio#224]
**Describe the bug**
I can't export  #220
![bug](https://user-images.githubusercontent.com/76905629/103491314-23409d80-4e66-11eb-8e5e-c66e1ce8e8be.JPG)

I tried hard, but I couldn't export.
help me,I tried to export hard-made music for an hour, but it was deleted because of the bug.

**Comment by Bentroen** [comment]
Thanks for reporting! However, we're keeping track of this problem in #220, so I'll close it in favor of the previous issue.
