### ISSUE TITLE
[Feature request] Changing octave range of the automatic transition

### ISSUE THREAD

**Issue by bluebackpack** [HielkeMinecraft/OpenNoteBlockStudio#229]
**Is your feature request related to a problem? Please describe.**
Automatic transition already exist, but they always transpose the notes to keep them within the 2 octave range.

**Describe the enhancement you'd like**
I want to transpose the notes keep them within the 3 octave range in importing midi.

**Additional context**
![2021-01-20](https://user-images.githubusercontent.com/77727649/105167773-7dc34480-5b5c-11eb-9ca5-51f3814aa07c.png)

**Comment by Bentroen** [comment]
Hello! Why exactly do you need the notes to be in a 3-octave range? Note blocks only supports two octaves, and this number was chosen to make it easier to import songs into Minecraft.
