### ISSUE TITLE
NBS crashing when trying to do anything after startup

### ISSUE THREAD

**Issue by Pewexxx** [HielkeMinecraft/OpenNoteBlockStudio#237]
**Describe the bug**
Basically, I can't create a new project, open an existing or go to the options, because clicking any button causes NBS crashing, showing this (please see additional context tab) error.
I've tried reinstalling NBS but it didn't help. The error started to appear after updating NBS to the newest version.

**To Reproduce**
1. Turn on NBS
2. Click start a new project
3. The error appears and the program crashes.

**Expected behaviour**
I expected normal usage of NBS and creating music using note blocks.

**Screenshots**

![image](https://user-images.githubusercontent.com/43313140/110687770-2bf47d80-81e1-11eb-95d8-c8f53bc3efbc.png)

**Additional context**
I have 2 midi devices (Arturia Keylab49 Essential and Pioneer DDJ-400), but I've tried to launch NBS while they had been both unplugged and the issue still existed.

THE ERROR:

>
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [11] out of range [11] - -1.mididevice_instrument(100110,11)
at gml_Script_midi_input_set_key
############################################################################################
gml_Script_midi_input_set_key (line -1)
gml_Script_draw_piano
gml_Script_control_draw
gml_Object_obj_controller_Draw_0 (line -1)
>

**Comment by MericGit** [comment]
Is the error the same for when no MIDI device is plugged in? 
![image](https://user-images.githubusercontent.com/41242144/110688821-9ee10280-81a7-11eb-81da-9dedd78ca5de.png)
Because looking at the MIDI device list that definitely seems out of the norm.

Could you send a screenshot of the error with no MIDI devices plugged in?

**Comment by Pewexxx** [comment]
I'll try to. The problem is that I've unplugged the physical midi devices, but these with "orb" seems to be virtual ones, so I need to figure out how to delete them. I'm gonna comment when that is done.

**Comment by Pewexxx** [comment]
OK, I've removed these "orb" midi devices AND the NBS works. The only problem is that a program called "Orb Composer" uses them and requires them to work properly, but I don't use this program now so I can let it go and work it out in my free time. Thank you for your help.
