### ISSUE TITLE
Error code, can't do anything

### ISSUE THREAD

**Issue by PikaAndrej** [HielkeMinecraft/OpenNoteBlockStudio#241]
**Describe the bug**
Everytime im trying to create new song or generate it from midi, the "Code Error" pops up

___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [11] out of range [11] - -1.mididevice_instrument(100110,11)
at gml_Script_midi_input_set_key
############################################################################################
gml_Script_midi_input_set_key (line -1)
gml_Script_draw_piano
gml_Script_control_draw
gml_Object_obj_controller_Draw_0 (line -1)

**To Reproduce**
1. Launch MNBS
2. Click "Create new song" or "Generate song out of MIDI file"

**Expected behavior**
I expected to generate anime OP's from midi files

**Screenshots**
![Minecraft_Note_Block_Studio_tI0R66vHEm](https://user-images.githubusercontent.com/82958977/115577656-4ab05e80-a2cd-11eb-95ff-e5d176373810.png)

**Additional context**
I had reinstalled the software twice.

**Comment by MericGit** [comment]
You are most likely using some virtual MIDI controller or such which breaks NBS. Disable them or uninstall them.

If that's not the case, could you upload the midi file here?

**Comment by Bentroen** [comment]
Does #237 describe your issue?

**Comment by PikaAndrej** [comment]
> You are most likely using some virtual MIDI controller or such which breaks NBS. Disable them or uninstall them.
> 
> If that's not the case, could you upload the midi file here?

thank's you a lot. idk how, but i had odd "Virtual MIDI" driver i never installed before, but thanks!
