### ISSUE TITLE
local variable <unknown built-in variable>(-1610512260, -2147483648) not set before reading it.

### ISSUE THREAD

**Issue by mckuhei** [HielkeMinecraft/OpenNoteBlockStudio#250]
**Describe the bug**
```
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object obj_controller:

local variable <unknown built-in variable>(-1610512260, -2147483648) not set before reading it.
at gml_Script_control_draw
############################################################################################
gml_Script_control_draw (line -1)
gml_Object_obj_controller_Draw_0 (line -1)
```

**To Reproduce**
1. Open file.
2. Play.
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/31839741/120917034-94b79d00-c6df-11eb-8d60-11c7f8389ed3.png)

**Additional context**
[Bergentruckung&asgore.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/6603818/Bergentruckung.asgore.zip)

**Comment by chenxi050402** [comment]
similar to issue #178

**Comment by mckuhei** [comment]
ok,there were have a smple way to repair file.

https://user-images.githubusercontent.com/31839741/120919783-e9faab00-c6ed-11eb-82ec-8cb0a1de7470.mp4
