### ISSUE TITLE
support OG nbs format

### ISSUE THREAD

**Issue by devomaa** [HielkeMinecraft/OpenNoteBlockStudio#251]
**Is your feature request related to a problem? Please describe.**
There is this one MC Mod called ComputerCraft and there is a program in it called "wave-amp" and it only supports the *OG* nbs format, not the ONBS format

**Describe the enhancement you'd like**
Support for exporting to *OG* nbs format

**Additional context**
nothing!

**Comment by chenxi050402** [comment]
![image](https://user-images.githubusercontent.com/62318879/121869793-fb1e6a00-cd34-11eb-99bc-0b21437ed769.png)
![image](https://user-images.githubusercontent.com/62318879/121869858-0b364980-cd35-11eb-96f8-8896da5a7a7e.png)

**Comment by devomaa** [comment]
Oh, thank you!

**Comment by devomaa** [comment]
wait, that doesnt work

**Comment by devomaa** [comment]
nvm im dum b
