### ISSUE TITLE
Measures aren't displayed correctly and lose their bold appearance

### ISSUE THREAD

**Issue by Non0reo** [HielkeMinecraft/OpenNoteBlockStudio#254]
**Describe the bug**
Some measures that are meant to be bold, sometimes disappear and become like other bars when I move the scroll bar

**To Reproduce**
I've downloaded the latest version of the software and this bug appeared

**Expected behavior**
These bars should be constantly bold

**Screenshots**
I attached a video that explain the problem

https://user-images.githubusercontent.com/70480609/126876089-44dc2405-0807-46fd-84cc-0aef7cdcb82e.mp4

**Comment by Bentroen** [comment]
Fixed in b8a71b7c1af3185957e71fdd6d18562ebfcc9c8c.
