### ISSUE TITLE
The Show old warning setting doesnt seem to work?

### ISSUE THREAD

**Issue by DevCarnage** [HielkeMinecraft/OpenNoteBlockStudio#256]
**Describe the bug**
When the checkbox for show old warning is disabled you'd expect it to not display warnings when opening an older nbs file but it still occurs
**To Reproduce**
1. Go to preferences and turn off the checkbox
2. Click on an older nbs file
3. See error (this will be the application showing the warning)

**Expected behavior**
No popups occur when the checkbox for warnings are disabled.

**Screenshots**
*It being turned off*
![image](https://user-images.githubusercontent.com/71865500/127404559-21ad591e-a0ad-489b-a536-92737b4cdf50.png)
*Warning popping up despite the above showing it unticked*
![image](https://user-images.githubusercontent.com/71865500/127404728-b5451be3-a410-4765-bed9-63216b44c652.png)

**Additional context**
I have tested having it turned off. Having it on, reinstalling the application and clearing the AppData etc

**Comment by chenxi050402** [comment]
The option will only work for NBS version v4, v3, v2, and v1, not the Classic version generated in the legacy version of Minecraft Note Block Studio.
