### ISSUE TITLE
keyboard color in themes (suggestion)

### ISSUE THREAD

**Issue by awful-coder** [HielkeMinecraft/OpenNoteBlockStudio#259]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my eyes hurt.

**Describe the enhancement you'd like**
Please make the white keys less white in the dark theme. If most everything else in the dark theme is darker, why can't the piano be darker?

**Comment by ShinkoNet** [comment]
In the next update, the new theme fluent (dark) will have a keyboard that isn't as white.

**Comment by Bentroen** [comment]
Added in d523dd06da3624951f5e9fab31053182e9f8ddb6.
