### ISSUE TITLE
Ability to choose original version for old structure .nbs

### ISSUE THREAD

**Issue by koca2000** [HielkeMinecraft/OpenNoteBlockStudio#26]
New structure of .nbs file solve the future problems, but when somebody decide to upgrade his .nbs file with custom instruments to new structure it will be broken. It would be helpful to add a dialog that pop-up when somebody try to open old file and let him select what is the origin Minecraft version of the file. Then it will be easy to choose right first custom instrument index and save the file in new format.

**Comment by HielkeMinecraft** [comment]
Ah of course. Good one :)

**Comment by octahedron80** [comment]
I suggest OpenNoteBlockStudio to have a new file extension (like .nbx, .nb2 for example, but I prefer .nbx) to distinguish between old and new format. The default format when saving must be the new format. If a user want to save as old format, just select .nbs. This approach is same as Microsoft Office does.

**Comment by koca2000** [comment]
The reason why Microsoft done it is that their product is paid and this was try to force you to buy a new Office. You could still save it to older format because some companies hadn't have a new one already. Also they made patch for Office 2003 to add compatibility with docx... This is free software and anyone can download latest version, so it is not necessary.

**Comment by ShinkoNet** [comment]
Added in upcoming update 3.7.0
![Uploading Runner_sT6LERti9x.png…]()
