### ISSUE TITLE
Input is slow on WINE.

### ISSUE THREAD

**Issue by pjalsGit** [HielkeMinecraft/OpenNoteBlockStudio#284]
**Describe the bug**
When you to type something in ONBS, like exporting a datapack, or changing tempo, it is extremely slow and hard to type.

**To Reproduce**
1. Go to a text box
2. Type something
3. See bug

**Expected behavior**
For it to be easy to type on input boxes.

**Screenshots**

https://user-images.githubusercontent.com/25231103/138850715-47d0b530-cc60-40fc-bdd7-2356aca8b4e4.mp4

**Additional context**
Here is my `uname -a`:
`Linux fedora 5.14.9-201.fsync.fc34.x86_64 #1 SMP Mon Oct 4 19:23:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
WINE version:
`wine-6.16 (Staging)`

**Comment by Bentroen** [comment]
Hello, and thanks for reporting the issue! This bug is not related to Wine, it occurs even in supported systems (as shown in the issue mentioned above). As such, I'll be closing this for now.
