### ISSUE TITLE
Feature request: Export to command block schematic

### ISSUE THREAD

**Issue by TheAlienDrew** [HielkeMinecraft/OpenNoteBlockStudio#30]
This would be useful for versions of Minecraft that don't support datapacks yet, and are nice in some old servers. I'd suggest looking at SethBling's MCEdit plugin that would convert the note blocks into command blocks for looking into.

**Comment by HielkeMinecraft** [comment]
I think servers should just use a plugin to play the nbs files. Here's a good one:
https://www.spigotmc.org/resources/noteblockapi.19287/

Or they could just update their servers of course. This program will always be aimed at the latest version of Minecraft.

Pull requests are always welcome though :)

**Comment by ShinkoNet** [comment]
NBS2CBS in NBS Mod 1.5 (a different fork/mod than this program) does this, but the command block structure takes ages to import, lags the world incredibly and relies on a countersys which's functioning varies by version. I think it should stay being datapack-only.
