### ISSUE TITLE
Interface is very small on high DPI displays

### ISSUE THREAD

**Issue by nikhiljha** [HielkeMinecraft/OpenNoteBlockStudio#31]
On high resolution displays the UI is tiny.

![image](https://user-images.githubusercontent.com/2773700/58438249-c2929180-8082-11e9-98c5-36cba982970f.png)

It would be nice if there were an option to increase UI scale, or otherwise detect DPI and scale everything accordingly. Not sure if it's doable with GML but a UI scale slider might work.

**Comment by Bentroen** [comment]
A scaling option could be useful not only for high DPI monitors, but for regular ones as well, when your song contains too many layers. Zooming out in a song would allow for more layers to be displayed on the screen at once, making navigation a lot easier (for example, when you have to select a big portion of a song).

**Comment by ShinkoNet** [comment]
This would take a while to implement but I do think it is useful

The menu/option bars should retain the same size, but the size of the note blocks being small like this should be an option.
For example, this song still requires you to scroll down to see everything, even with the high DPI.
![Capture](https://user-images.githubusercontent.com/10773386/62499786-47d6b700-b827-11e9-817b-b160922d4ae7.PNG)

I'll see if I can implement this, but Note Block Studio's engine is rather rigid.

**Comment by vberlier** [comment]
Any update on this? I'm having the same problem.

![image](https://user-images.githubusercontent.com/24430071/112716505-196b8b00-8ee7-11eb-8837-2d50688c376a.png)

**Comment by Bentroen** [comment]
@vberlier Hello! Sadly, changing your scaling settings on Windows remains the only way to remedy this. As version 4.0 will be delayed a bit, I'm currently looking for a "hacky" solution in the current version, which would be to make everything half the size, and then scale it to the whole window. Since the program is a bit weird on how it draws things, I'm not sure if that would work at all, but I'll make an update here as soon as I give it a go. :)

**Comment by Bentroen** [comment]
**Update:** I finally got it to work! I'll try to ship an update as soon as possible with this patch. 😄 

(please don't mind my regular screen size haha)

https://user-images.githubusercontent.com/29354120/114827552-35a07080-9d9f-11eb-8ff8-76dc19948d9e.mp4
