### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by tristan2998** [HielkeMinecraft/OpenNoteBlockStudio#32]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_buffer_read_string_int
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

Similar to other cases, but a little different, like #8

**Comment by ShinkoNet** [comment]
Have you tried deleting your settings.file in /data?

**Comment by tristan2998** [comment]
Will give it a go. Also I didn't realise the fan port was made by
shinkonet. I love your midis!

**Comment by DarkBrave** [comment]
this helped me! Thanks!

**Comment by XGMCLOLCrazE** [comment]
I was having this same issue, but I can't find settings.file nor /data.

Where is it located?

**Comment by koca2000** [comment]
Duplicate of #6

**Comment by tristan2998** [comment]
Thanks again for the help!
