### ISSUE TITLE
Huge Issue. FATAL ERROR

### ISSUE THREAD

**Issue by jmancox330** [HielkeMinecraft/OpenNoteBlockStudio#39]
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_buffer_read_string_int
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

This is the error I am getting. I had the original version of nbs but then I installed your version, about 6 hours later the original version turned into your version, and wouldn't work. When I try installed your version or the original version, I get that error.

**Comment by diamondriverplays** [comment]
having the same problem as you

**Comment by ShinkoNet** [comment]
The original NBS and this version are conflicting and probably installed in the same place. Use the .zip version instead of the installer, or remove the settings.file if necessary.

**Comment by jmancox330** [comment]
Thank you, installing the .zip file worked!
