### ISSUE TITLE
fatal error on start up please help

### ISSUE THREAD

**Issue by diamondriverplays** [HielkeMinecraft/OpenNoteBlockStudio#40]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_buffer_read_string_int
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

**Comment by HielkeMinecraft** [comment]
Looks to me like something went wrong when updating Note Block Studio. Uninstalling the program and installing it again will help. You can also remove the settings.file file located at C:\Users\yourname\Minecraft Note Block Studio\Data
