### ISSUE TITLE
Issue when playing Datapack functions.

### ISSUE THREAD

**Issue by Ronezkj15** [HielkeMinecraft/OpenNoteBlockStudio#42]
Whenever trying to play a command in a command block, it doesn't happen, I've looked through the commands and the only reason its happening is everything is to @s. I'd request it to put it to @p so you can run it through command blocks.

**Comment by ShinkoNet** [comment]
The datapack handles more than just the /playsound commands to play the notes, so running a /playsound command generated by the datapack without using the actual datapack will not work.

If you are interested in exporting Note Block Studio songs to command blocks, please use NBS2CBS:
https://www.youtube.com/watch?v=pjeNj1miz8A
