### ISSUE TITLE
Note blocks in the first tick of a song don't play when selected

### ISSUE THREAD

**Issue by Edude42** [HielkeMinecraft/OpenNoteBlockStudio#47]
When the first note of the song is selected, it ignores just that note.
Example: https://dl.edude.xyz/o/OpenNoteBlockStudio_Odd_Bug.mp4
_Had to use my own host because YouTube wasn't working._

Edit: Had to change link because I changed my hosting solution.

**Comment by ShinkoNet** [comment]
That's been an issue since the older version of note block studio. You just have to deselect the part. As it's minor, I don't think we will fix it anytime soon, but i'll take a look anyway.
