### ISSUE TITLE
long song broke when i tried to export a midi song to a datapack

### ISSUE THREAD

**Issue by Benzeel** [HielkeMinecraft/OpenNoteBlockStudio#49]
___________________________________________ ############################################################################################ FATAL ERROR in action number 1 of Draw Event for object obj_controller: Push :: Execution Error - Variable Index [0,17] out of range [1,15] - 0.<unknown variable>(100200,17) at gml_Script_dat_generate ############################################################################################ -------------------------------------------------------------------------------------------- stack frame is gml_Script_dat_generate (line -1) gml_Script_datapack_export gml_Script_draw_window_datapack_export gml_Script_draw_windows gml_Script_control_draw gml_Object_obj_controller_Draw_0

The song:
[nbs.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/3346865/nbs.zip)

**Comment by TIMETSS** [comment]
I got a same problem....
