### ISSUE TITLE
Datapack suggestion: sequential playing

### ISSUE THREAD

**Issue by tryashtar** [HielkeMinecraft/OpenNoteBlockStudio#5]
Taking a look at the source here, I have a bit of a suggestion for the generation of the data pack. (I'd test it myself but it appears to crash -- not the issue I'm reporting here though :P)

From what I can tell, it generates a function with one `/playsound` command for each note in the song, and it plays as a score increases, with every note mapped to the time during which it should play. Ultimately, this isn't very efficient for long songs, as tons of score checks are happening every tick.

I have a more optimal solution here which utilizes a sequence of functions with command blocks (sorry, organization not great in this project of mine):
https://github.com/tryashtar/nbs-functions/blob/master/nbsreader/Model.cs#L154

There is one function for every time division, and it plays the notes necessary at that time. Then, it does a `/data merge` to insert the next function into the command block. The next notes then play next tick, and prepare the next function, and so on. It only runs as many commands per tick as there are notes that tick, instead of one command per note in the entire song.

Anyway, I think an option like this would be more optimal for the data pack. The tick tag and pause/play/looping functions would no longer be necessary, as the playback would be handled by a single repeating command block, which could be powered or depowered to pause or play the song. The only potential disadvantage to my knowledge is the fact that lots of functions are generated, however they can be coalesced somewhat (I have some methods in my project that do as much).

**Comment by HielkeMinecraft** [comment]
While I do see the potential in your idea, I doubt it's worth it right now. It definitely isn't optimal.

The beautiful thing about the datapack export is that it allows note block music to be played without any actual blocks. 

With this suggestion there always need to be command blocks somewhere. These command blocks must always be loaded, so you have to keep them around the player or in spawn chunks. This is not ideal as spawn chunks aren't the same for every world, and I just don't want to edit blocks in the world.

Also, it looks like the command blocks need to call a function every tick. Even if there isn't a sound to play, it will still call the function that only edits the block data every tick. 

And what if multiple people wanted to listen to different songs? how would the note blocks be able to handle this? I don't think that's possible.

Lastly, editing block data every tick is quite a bit more expensive than just checking integers (I think). Can you provide proof that your method is actually more efficient? Like with large songs perhaps?

**Comment by tryashtar** [comment]
All good points. I guess for the most part it depends on your goals (local vs global music, and entities vs blocks). And I can see how the former of each would be a bit more flexible.

While editing block data every tick is certainly more expensive than a simple score check, it remains -- more or less -- O(1) commands per tick. Whereas with the single function solution, you're running one cheap command for every note in the _entire song_ every tick.

Honestly, your rationale is enough that I no longer care about switching to this kind of system (i.e. you can close this issue). But I am curious about getting some actual performance benchmarks -- find exactly how many notes it takes to break even. I'll get back to you on that.

**Comment by HielkeMinecraft** [comment]
Yeah some benchmarks would be really interesting! I wonder how many command it takes to brings Minecraft to its knees >:D

Also, no problem! Glad to make people happy :)
