### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by EvolutionPixels** [HielkeMinecraft/OpenNoteBlockStudio#51]
![07 09 2019](https://user-images.githubusercontent.com/12032252/60870405-74ec7580-a239-11e9-9ef4-2284d5c0e197.PNG)

This error occurs in the new release version of NBS 3.5.0 when importing the midi file and playing it.
This error was not in NBS 3.4.0 when importing midi files and then playing the imported one.

I stick the used midi file on error.
[midi_file.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/3371888/midi_file.zip)

**Comment by ShinkoNet** [comment]
Thanks for the info. I think I know what is causing this, i'll fix it soon.

**Comment by EvolutionPixels** [comment]
> 
> 
> Thanks for the info. I think I know what is causing this, i'll fix it soon.

Ok. Thanks for the response.

**Comment by ShinkoNet** [comment]
I wasn't having any issue when loading and playing the MIDI myself... I still tried to fix the issue, can you try this build for me?
[Minecraft Note Block Studio.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/3389397/Minecraft.Note.Block.Studio.zip)
If it still doesn't work, try importing the midi, saving, exiting, then reloading the song.

**Comment by EvolutionPixels** [comment]
> 
> 
> I wasn't having any issue when loading and playing the MIDI myself... I still tried to fix the issue, can you try this build for me?
> [Minecraft Note Block Studio.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/3389397/Minecraft.Note.Block.Studio.zip)
> If it still doesn't work, try importing the midi, saving, exiting, then reloading the song.

It works, hooray. Now when importing a midi file and playing it, the error does not crash!
Thanks for correcting the error!

And this corrected version needs to be published in releases with an error correction mark.

**Comment by EvolutionPixels** [comment]
Well, since this error has been corrected, this issue can be closed.
