### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by Creepercdn** [HielkeMinecraft/OpenNoteBlockStudio#54]
I'm use 60fps mode and playing in stereo.
This is log:
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [0,23] out of range [1,18] - -1.layerstereo(100112,23)
at gml_Script_control_draw
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_control_draw (line -1)
gml_Object_obj_controller_Draw_0

**Comment by EvolutionPixels** [comment]
This error has already been fixed.
This link you will find a build with a bug fix.

https://github.com/HielkeMinecraft/OpenNoteBlockStudio/issues/51
