### ISSUE TITLE
The app keeps crashing and I get this error:

### ISSUE THREAD

**Issue by burritopower44** [HielkeMinecraft/OpenNoteBlockStudio#57]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [0,27] out of range [1,23] - -1.layerstereo(100112,27)
at gml_Script_control_draw
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_control_draw (line -1)
gml_Object_obj_controller_Draw_0

**Comment by EvolutionPixels** [comment]
This error has already been fixed.
This link you will find a build with a bug fix.
Just download this build to link.

https://github.com/HielkeMinecraft/OpenNoteBlockStudio/issues/51#issuecomment-511167853
