### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Volcaniks** [HielkeMinecraft/OpenNoteBlockStudio#58]
Whenever I try and import a midi file it always gives me the following error message.

Program:

This application has requested the Runtime to terminate in an unusual way.
Please contact the applications support team for more information.

**Comment by ShinkoNet** [comment]
Fixed in latest update, i think

**Comment by jamesmule** [comment]
Fun fact, I literally downloaded 3.5.0 seconds before you uploaded 3.5.1 and immediately crashed on a MIDI import. 3.5.1 works for me.
