### ISSUE TITLE
FATAL ERROR after updating? Fix here!

### ISSUE THREAD

**Issue by HielkeMinecraft** [HielkeMinecraft/OpenNoteBlockStudio#6]
When updating to a new version, it may give a FATAL ERROR when you load NBS. 
Like here:

![image](https://user-images.githubusercontent.com/42968178/54318745-991bab00-45e7-11e9-8c3b-94e1ad06a6a4.png)

To fix this, you can either: 
**1.** Remove Note Block Studio completely and install it again
**2.** Delete the settings.onbs file located inside the Data folder.   

In both cases, your settings will unfortunately be reset.

**Comment by burritopower44** [comment]
I tried both reinstalling and removing settings.onbs. Still getting this message. Note Block Studio no longer loads. 3.6.0

**Comment by HielkeMinecraft** [comment]
Can you send your error message?

**Comment by burritopower44** [comment]
It’s the same issue as the picture above.

**Comment by Bentroen** [comment]
Settings are now stored in an .ini file since 3.7.0, so I'm closing this issue.
