### ISSUE TITLE
Not really an issue but is still a bit annoying

### ISSUE THREAD

**Issue by enderGuardian46** [HielkeMinecraft/OpenNoteBlockStudio#60]
This is not really an issue but I think you should make it possible to run the installer for the newer version without having to manually uninstall the older one. I mean, if it have to uninstall the old version before installing, why can't it do that automatically when I run the installer?

**Comment by enderGuardian46** [comment]
I get this if I update without uninstalling the old version: 
![Error](https://user-images.githubusercontent.com/50124529/62009212-ed6d9480-b15c-11e9-996b-e71bea8e5e32.PNG)

**Comment by ShinkoNet** [comment]
Ah, yeah, the crash after updating will be fixed next release. Also, due to how game maker works, this issue of manually updating has always been a bother.

**Comment by ShinkoNet** [comment]
Fixed crash, but manual updates will still be the same.

**Comment by AlsoScratch** [comment]
So I don't have to uninstall anymore before updating?
