### ISSUE TITLE
Dark theme scrollbar

### ISSUE THREAD

**Issue by Edude42** [HielkeMinecraft/OpenNoteBlockStudio#61]
I very much enjoy the dark theme, but the scrollbars can be really confusing to me. Because they have a similar gradient and color, the thumb and bar blend together.
![image](https://user-images.githubusercontent.com/34699884/62067283-59093d80-b201-11e9-874e-778391d83864.png)

**Comment by HielkeMinecraft** [comment]
Yeah I noticed this one too. This is a bug and will be fixed soon :).
