### ISSUE TITLE
Blank Instrument Icons

### ISSUE THREAD

**Issue by Bitzel** [HielkeMinecraft/OpenNoteBlockStudio#62]
**Describe the bug**
The noteblock instrument icons are blank

**To Reproduce**
1. Go to preferences
2. Click appearance
3. Click show instrument icons
4. Look at placed notes, the icons are blank

**Screenshots**

![image](https://user-images.githubusercontent.com/53413916/62082132-c88b2700-b219-11e9-97ad-33a7cbac0b70.png)

**Comment by ShinkoNet** [comment]
ah, thanks, i'll get this fixed next released.

**Comment by HielkeMinecraft** [comment]
Don't bother, I got this :)
