### ISSUE TITLE
Mass MP3 export

### ISSUE THREAD

**Issue by Edude42** [HielkeMinecraft/OpenNoteBlockStudio#63]
I have a long list of .nbs files I need to convert to MP3 files. It's really tedious when I have to open each song, export as MP3, then repeat.

It would be really nice if there was a way to select a bunch and convert them all. Sort of like a queue that will automatically export them all one by one.

![mcnbs](https://user-images.githubusercontent.com/34699884/62170552-c13b4a80-b2f9-11e9-9180-3049f16b15c6.png)

**Comment by ShinkoNet** [comment]
I think that if a seperate program is developed to do this, it would be good. The current MP3 export relies on a mixture of gamemaker code and proprietary libraries, which don't support the new stereo changes either.

**Comment by HielkeMinecraft** [comment]
Yeah this really isn't something that NBS should do. A converter program is what you need.
