### ISSUE TITLE
'Usabiliy' typo in Preferences

### ISSUE THREAD

**Issue by Bentroen** [HielkeMinecraft/OpenNoteBlockStudio#64]
There's a long-standing typo in the Preferences window, where the 'Usability' tab is written as 'Usabiliy'.

![Typo](https://user-images.githubusercontent.com/29354120/62416834-687cf200-b618-11e9-80cc-af27c1f7835f.PNG)

**Comment by HielkeMinecraft** [comment]
Wow you really have an eye for details! 👍
