### ISSUE TITLE
Program icon no longer uses isometric view

### ISSUE THREAD

**Issue by Bentroen** [HielkeMinecraft/OpenNoteBlockStudio#65]
The legacy program icon used to picture a note block using isometric view, i.e. lines are parallel (probably taken from Minecraft Wiki, as most block images there are rendered in external programs rather than taken from Minecraft).

The new icon, on the other hand, seems to have been taken from a Minecraft screenshot, which uses perspective rather than isometric view. Check comparison below:

![Comparison](https://user-images.githubusercontent.com/29354120/62417047-b7c52180-b61c-11e9-865d-6fbab78543cf.png)

Not only the isometric projection looks better, but it's also widely used when making program icons that contain cubes, which includes Minecraft Launcher and Minecraft itself.

With that in mind, I made a new icon for the program, which retains both the isometric projection from the old icon, as well as the new texture and note color in the new icon:

![New](https://user-images.githubusercontent.com/29354120/62417145-21462f80-b61f-11e9-84b4-9e4e608e3811.png)

**Comment by ShinkoNet** [comment]
Thanks, we'll use it for the next release.

**Comment by HielkeMinecraft** [comment]
Haha yeah I tried to match the old one as close as possible (setting FOV very low), and it still wasn't perfect. Thanks for making that icon :)
