### ISSUE TITLE
Different instrument shapes should have its own toggle

### ISSUE THREAD

**Issue by Bentroen** [HielkeMinecraft/OpenNoteBlockStudio#66]
The recent implementation of different note block shapes according to the instrument was very neat. Though, I still prefer the original look -- and being a dark theme user, I'm forced to stay with the new icons due to them being tied to dark mode.

To circumvent that and allow more customizability, I suggest that a toggle, 'Use different shapes for each instrument', is added under the 'Appearance' tab in Preferences.

**Comment by ShinkoNet** [comment]
The new sprites overwrote the old sprites, i'd have to add them again. I'm also having a tough time with getting preference settings to actually work. I'll keep it in mind.

**Comment by HielkeMinecraft** [comment]
Luckily the old sprites are still there. I added the option in the appearance tab :)
