### ISSUE TITLE
Export each layer separately for mixing

### ISSUE THREAD

**Issue by jukmifgguggh1337** [HielkeMinecraft/OpenNoteBlockStudio#68]
Just add an option somewhere that allows each layer to be exported as mp3 separately
Or it could be a feature for the export as mp3 option where it takes into account the locked or soloed layers

It might be difficult to put in the program but i'll still ask since it'll be pretty helpful to me at least
thanks

**Comment by ShinkoNet** [comment]
you might as well load the note block samples and compose in another program like OpenMPT for the same effect, and just export the MP3s seperately with their batch-processing export.

**Comment by HielkeMinecraft** [comment]
When exporting as MP3, it will now ask you if you want to include locked layers. I know this doesn't fully cover your suggestion, but I think it's a good middle ground. :)
![image](https://user-images.githubusercontent.com/42968178/62701073-af396600-b9e3-11e9-82dc-a0dcdf1da6eb.png)

**Comment by ShinkoNet** [comment]
Yeah, that sounds good. No batch support would be added so you'll have to just edit the layers seperately each time you export.

**Comment by ThatOneJose95** [comment]
How about instead of export all but locked, only locked?

**Comment by Bentroen** [comment]
@ThatOneJose95 Try enabling solo on the layers you want to export. It should behave exactly like that.
