### ISSUE TITLE
when opening the app it shows a code and not opening or working

### ISSUE THREAD

**Issue by Kinga192** [HielkeMinecraft/OpenNoteBlockStudio#69]
it shows this code
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

what do i do?

**Comment by ShinkoNet** [comment]
https://github.com/HielkeMinecraft/OpenNoteBlockStudio/issues/6

Delete your settings.onbs file in /data

**Comment by Kinga192** [comment]
thank you shinko!
