### ISSUE TITLE
Fatal Error on MP3 export

### ISSUE THREAD

**Issue by JDRLGaming** [HielkeMinecraft/OpenNoteBlockStudio#70]
i get a fatal error when i try to export as an mp3. i need this feature working for my video on monday so its really important to me. please fix it

**Comment by HielkeMinecraft** [comment]
Can we have the .nbs file you want to export? Right now we don't know whats wrong. Please include a screenshot of the error.

**Comment by JDRLGaming** [comment]
![Image2](https://user-images.githubusercontent.com/54002009/62847698-82c96680-bccf-11e9-84e1-7d3555efa681.png)

I have attached a screenshot of the error as requested.
[Note Block Song.zip](https://github.com/HielkeMinecraft/OpenNoteBlockStudio/files/3491154/Note.Block.Song.zip)

my note block songs use many custom instruments so i have included a zip file with all my songs and custom instruments as i don't know what you want the file for.

**Comment by ShinkoNet** [comment]
Try converting your custom instruments from .mp3 and .wav to .ogg format. Just tried Imagine Dragons - Demons and it saved fine.

**Comment by JDRLGaming** [comment]
ill try the conversion but i kinda need the custom instruments for some of my songs to sound right,

**Comment by JDRLGaming** [comment]
I just tried Taylor Swift - Love Story with the .ogg format and it still crashed the program, However it did work fine without custom instruments, unfortunately this is no use to me because i use multiple custom instruments in my songs

**Comment by JDRLGaming** [comment]
kk, i think i might have found a fix, i just created a short song using only a custom instrument and it worked fine, so i might have to export the custom instruments separately and combine the audio while editing, but recording the audio via audacity might be a problem because for many of my songs the playback is a bit too slow cuz my computer is old and slow. i will try it anyway though, thanks

**Comment by JDRLGaming** [comment]
nevermind, my fix did not work. ill have to try audacity.

**Comment by JDRLGaming** [comment]
im really confused now, i have managed to export Imagine Dragons - Demons with all custom instruments and it saved fine but I just tried 5SOS - Youngblood and Note Block Studio Crashed again??

**Comment by octahedron80** [comment]
I also confront same error as above. I just installed and use it today. If you want to see message, it is here:

```
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [0,38] out of range [1,34] - -1.lockedlayer(100211,38)
at gml_Script_mp3_export
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_mp3_export (line -1)
gml_Script_draw_window_mp3_export
gml_Script_draw_windows
gml_Script_control_draw
gml_Object_obj_controller_Draw_0
```

The song here -> [Dropbox](https://www.dropbox.com/s/3hledxrk4zmoo8b/moonlight_densetsu.nbs?dl=0)

**Comment by JDRLGaming** [comment]
> I also confront same error as above. I just installed and used it today. (I had used David's program for some time and it was fine.) If you want to see message, it is here:
> 
> ```
> ___________________________________________
> ############################################################################################
> FATAL ERROR in
> action number 1
> of Draw Event
> for object obj_controller:
> 
> Push :: Execution Error - Variable Index [0,38] out of range [1,34] - -1.lockedlayer(100211,38)
> at gml_Script_mp3_export
> ############################################################################################
> --------------------------------------------------------------------------------------------
> stack frame is
> gml_Script_mp3_export (line -1)
> gml_Script_draw_window_mp3_export
> gml_Script_draw_windows
> gml_Script_control_draw
> gml_Object_obj_controller_Draw_0
> ```
> 
> The song here -> [Dropbox](https://www.dropbox.com/s/3hledxrk4zmoo8b/moonlight_densetsu.nbs?dl=0)

**Comment by JDRLGaming** [comment]
Hi, i just experienced the problem again with the song you have provided. the issue seems to have gotten worse because my songs used to only crash when i used custom instruments but would save fine without them. but your song crashed the program with no custom instruments.

**Comment by JDRLGaming** [comment]
hi, i just exported 5SOS - Youngblood as an mp3. it uses 10,000 notes and 14 custom instruments and it saved fine. i can send you the file i if it would be helpful

**Comment by octahedron80** [comment]
I look forwards to the next release. Thanks.
