### ISSUE TITLE
Crashing when opening

### ISSUE THREAD

**Issue by GellertBorsay** [HielkeMinecraft/OpenNoteBlockStudio#80]
I can't open MNS since version 3.6.0

I got this error message:

___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Create Event
for object obj_controller:

Attempting to read from outside the buffer, returning 0
at gml_Script_buffer_read_byte
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_buffer_read_byte (line -1)
gml_Script_load_settings
gml_Script_control_create
gml_Object_obj_controller_Create_0

**Comment by HielkeMinecraft** [comment]
Probably another case of #6 
If that doesn't work, let me know.
