### ISSUE TITLE
Only imports one channel

### ISSUE THREAD

**Issue by Basketing** [HielkeMinecraft/OpenNoteBlockStudio#85]
when ever you try to import a MIDI file it only imports through one instrument 

1. import any MIDI file and there will be only one channel

![Capture](https://user-images.githubusercontent.com/55329041/64912376-4210a300-d6fc-11e9-9d4a-273b4f616aca.PNG)

**Comment by ShinkoNet** [comment]
It's fine on my end importing any midi. You sure the MIDI file itself is OK?
Can you send the MIDI file?

**Comment by creeperreaper206** [comment]
having the same problem

**Comment by creeperreaper206** [comment]
im also using midi from musescore

**Comment by Bentroen** [comment]
Many MIDIs, especially those that only contain a single instrument (in this case piano), only consist of a single track. In that case, it's not an issue with the program - you'll have to split the notes manually if you want to use multiple instruments.
