### ISSUE TITLE
Replacing note with custom instrument note does not properly trigger compatibility check

### ISSUE THREAD

**Issue by Marcono1234** [HielkeMinecraft/OpenNoteBlockStudio#88]
**Describe the bug**
Replacing a note for a normal instrument with a note for a custom instrument does not properly trigger the compatibility check. It says that the song is compatible even though it isn't. And when removing the note, it incorrectly says it is not compatible even though it now is.

**To Reproduce**
1. Place a harp note
2. Add a new custom instrument
3. Select the custom instrument
4. Click on the harp note placed in step 1 (i.e. replace the note)
:x: The compatibility check in the top right says the song is compatible, even though it isn't
5. Remove the custom note (right click)
:x: The compatibility check in the top right incorrectly says the song is incompatible

**Version**
3.6.0

**Comment by Bentroen** [comment]
Fixed in next release.
