### ISSUE TITLE
"Song stats..." are not correctly reset when creating new song

### ISSUE THREAD

**Issue by Marcono1234** [HielkeMinecraft/OpenNoteBlockStudio#89]
**Describe the bug**
When creating a new song, the "Song stats..." (under "Settings") are not correctly reset. They still list the blocks from the previous song(s) and also show incorrect percentages.

**To Reproduce**
1. Create a new song and place some notes
2. Create a new song (discard the current one)
3. Look under "Settings" > "Song stats..."
:x: It still shows the blocks placed from the first song, with incorrect percentages

**Screenshots**
![Song stats](https://user-images.githubusercontent.com/11685886/66860297-38918980-ef8d-11e9-8c22-9539d7d8b899.png)

**Version**
3.6.0

**Comment by ShinkoNet** [comment]
Thanks. This is an issue in the reset script, I'll check which bits need to be cleared in a reset.
