### ISSUE TITLE
Track names are missing

### ISSUE THREAD

**Issue by AlsoScratch** [HielkeMinecraft/OpenNoteBlockStudio#9]
Track name don't show up when importing
![Capture](https://user-images.githubusercontent.com/48752273/54672988-50f31000-4b34-11e9-9ee2-6c49afe4e7d1.JPG)

**Comment by HielkeMinecraft** [comment]
Looks like naming the layers also doesn't work. I bet it's something with the new fonts. Looking into it.

**Comment by HielkeMinecraft** [comment]
Fixed in 7ad9007bae1e28283fce4c36b067fd203105153b.

**Comment by AlsoScratch** [comment]
What do I do then?

**Comment by AlsoScratch** [comment]
What do I do next?

**Comment by AlsoScratch** [comment]
Will there be an update?

**Comment by HielkeMinecraft** [comment]
Yeah, creating one right now!
