### ISSUE TITLE
Error when scrolling down to the 202nd layer

### ISSUE THREAD

**Issue by IoeCmcomc** [HielkeMinecraft/OpenNoteBlockStudio#92]
**Describe the bug**
An error appeared when trying to scroll the edit area down to the 202nd line (layer) or more.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a new file (or any file)
2. Scroll down to the 202nd layer or more (may need to put some note to expand scrolling range)
See error

**Expected behaviour**
It should display these layers properly.

**Screenshots**
![ONBS error screenshot 1 364](https://user-images.githubusercontent.com/53734763/67137497-a4f7db80-f260-11e9-9a2b-e3a6275ff5ca.png)

**Error message**
```
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_controller:

Push :: Execution Error - Variable Index [0,301] out of range [1,301] - -5.text_exists(100054,301)
at gml_Script_draw_text_edit
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Script_draw_text_edit (line -1)
gml_Script_control_draw
gml_Object_obj_controller_Draw_0
```

**Infomation**
OS: Windows 7 32bit
Program version: 3.6.0

**Comment by ShinkoNet** [comment]
Probably ran out of IDs for text boxes. Will investigate.

**Comment by Bentroen** [comment]
Extending the limit would only postpone the issue; ideally, we should make it create more text boxes on demand, so the limit would only be the array index limit in GameMaker (32,000).

**Comment by Bentroen** [comment]
The layer limit was expanded to 10,000 for the next version. It's still gonna crash when that layer is reached, but it's a more reasonable limit than 200. A "proper" fix, such as preventing the user from scrolling beyond that layer, may be applied in the future.
