### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by RobertSchuh** [HielkeMinecraft/OpenNoteBlockStudio#93]
I get this crash when I try to open the installled .exe

Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x0062c822).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:0062c822 ESP:0033ed40 EBP:00000001 EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:00002068 ECX:00000280 EDX:00000000
 ESI:000001e0 EDI:00000280
Stack dump:
0x0033ed40:  00000000 00000000 00000000 000001e0
0x0033ed50:  7e289778 0033edf4 0033ed88 7bc51c9d
0x0033ed60:  7dc612df 007c17f4 f7d7afeb 7e289000
0x0033ed70:  7e285fd0 00adc14c 0033edf8 7e285f85
0x0033ed80:  00000000 7e289778 7e2868a8 7e286800
0x0033ed90:  00000000 7e286764 00000000 00000020
Backtrace:
=>0 0x0062c822 in minecraft note block studio (+0x22c822) (0x00000001)
0x0062c822: movl	0x0(%eax),%ecx
Modules:
Module	Address			Debug info	Name (91 modules)
PE	  400000-  b18000	Export          minecraft note block studio
ELF	7b800000-7ba54000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba54000	\               kernel32
ELF	7bc00000-7bcda000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcda000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7d7e0000-7d815000	Deferred        uxtheme<elf>
  \-PE	7d7f0000-7d815000	\               uxtheme
ELF	7d815000-7d81c000	Deferred        libxxf86vm.so.1
ELF	7d81c000-7d820000	Deferred        libxinerama.so.1
ELF	7d820000-7d827000	Deferred        libxdmcp.so.6
ELF	7d827000-7d82b000	Deferred        libxau.so.6
ELF	7d82b000-7d851000	Deferred        libxcb.so.1
ELF	7d851000-7d99c000	Deferred        libx11.so.6
ELF	7d99c000-7d9b1000	Deferred        libxext.so.6
ELF	7d9d3000-7da60000	Deferred        winex11<elf>
  \-PE	7d9e0000-7da60000	\               winex11
ELF	7dadc000-7db06000	Deferred        libexpat.so.1
ELF	7db06000-7db4f000	Deferred        libfontconfig.so.1
ELF	7db4f000-7db7a000	Deferred        libpng12.so.0
ELF	7db7a000-7dc2a000	Deferred        libfreetype.so.6
ELF	7dc4c000-7dc62000	Deferred        dwmapi<elf>
  \-PE	7dc50000-7dc62000	\               dwmapi
ELF	7dc62000-7dc9e000	Deferred        winspool<elf>
  \-PE	7dc70000-7dc9e000	\               winspool
ELF	7dc9e000-7dd83000	Deferred        comdlg32<elf>
  \-PE	7dca0000-7dd83000	\               comdlg32
ELF	7dd83000-7deb0000	Deferred        oleaut32<elf>
  \-PE	7dda0000-7deb0000	\               oleaut32
ELF	7deb0000-7df3a000	Deferred        gdiplus<elf>
  \-PE	7dec0000-7df3a000	\               gdiplus
ELF	7df3a000-7df6e000	Deferred        ws2_32<elf>
  \-PE	7df40000-7df6e000	\               ws2_32
ELF	7df6e000-7df98000	Deferred        msacm32<elf>
  \-PE	7df70000-7df98000	\               msacm32
ELF	7df98000-7e014000	Deferred        rpcrt4<elf>
  \-PE	7dfa0000-7e014000	\               rpcrt4
ELF	7e014000-7e143000	Deferred        ole32<elf>
  \-PE	7e030000-7e143000	\               ole32
ELF	7e143000-7e1fb000	Deferred        winmm<elf>
  \-PE	7e150000-7e1fb000	\               winmm
ELF	7e1fb000-7e20f000	Deferred        psapi<elf>
  \-PE	7e200000-7e20f000	\               psapi
ELF	7e20f000-7e274000	Deferred        dbghelp<elf>
  \-PE	7e220000-7e274000	\               dbghelp
ELF	7e274000-7e28a000	Deferred        d3d11<elf>
  \-PE	7e280000-7e28a000	\               d3d11
ELF	7e28a000-7e3a8000	Deferred        opengl32<elf>
  \-PE	7e2b0000-7e3a8000	\               opengl32
ELF	7e3a8000-7e4da000	Deferred        wined3d<elf>
  \-PE	7e3c0000-7e4da000	\               wined3d
ELF	7e4da000-7e500000	Deferred        dxgi<elf>
  \-PE	7e4e0000-7e500000	\               dxgi
ELF	7e500000-7e5f5000	Deferred        comctl32<elf>
  \-PE	7e510000-7e5f5000	\               comctl32
ELF	7e5f5000-7e81e000	Deferred        shell32<elf>
  \-PE	7e600000-7e81e000	\               shell32
ELF	7e81e000-7e894000	Deferred        shlwapi<elf>
  \-PE	7e830000-7e894000	\               shlwapi
ELF	7e894000-7e900000	Deferred        advapi32<elf>
  \-PE	7e8a0000-7e900000	\               advapi32
ELF	7e900000-7ea17000	Deferred        gdi32<elf>
  \-PE	7e910000-7ea17000	\               gdi32
ELF	7ea17000-7eb65000	Deferred        user32<elf>
  \-PE	7ea30000-7eb65000	\               user32
ELF	7eb65000-7eb8c000	Deferred        mpr<elf>
  \-PE	7eb70000-7eb8c000	\               mpr
ELF	7eb8c000-7eba7000	Deferred        libz.so.1
ELF	7eba7000-7ec1e000	Deferred        wininet<elf>
  \-PE	7ebb0000-7ec1e000	\               wininet
ELF	7ec1e000-7ec31000	Deferred        libnss_files.so.2
ELF	7ec31000-7ec3e000	Deferred        libnss_nis.so.2
ELF	7ec3e000-7ec59000	Deferred        libnsl.so.1
ELF	7ef89000-7efde000	Deferred        libm.so.6
ELF	7efe7000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7a8c000-f7ad5000	Deferred        dinput<elf>
  \-PE	f7a90000-f7ad5000	\               dinput
ELF	f7ad5000-f7af1000	Deferred        dinput8<elf>
  \-PE	f7ae0000-f7af1000	\               dinput8
ELF	f7af1000-f7b15000	Deferred        imm32<elf>
  \-PE	f7b00000-f7b15000	\               imm32
ELF	f7b5b000-f7b70000	Deferred        xinput1_3<elf>
  \-PE	f7b60000-f7b70000	\               xinput1_3
ELF	f7b7c000-f7b81000	Deferred        libdl.so.2
ELF	f7b81000-f7d37000	Deferred        libc.so.6
ELF	f7d37000-f7d54000	Deferred        libpthread.so.0
ELF	f7d56000-f7d60000	Deferred        libnss_compat.so.2
ELF	f7d76000-f7f2b000	Dwarf           libwine.so.1
ELF	f7f2c000-f7f51000	Deferred        ld-linux.so.2
ELF	f7f54000-f7f56000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	0000001d    0
	0000001c    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001b    0
	00000018    0
	00000017    0
	00000013    0
00000019 plugplay.exe
	0000001f    0
	0000001e    0
	0000001a    0
00000021 explorer.exe
	00000023    0
	00000022    0
0000003a Minecraft Note Block Studio.exe
	0000000b    0
	00000042    0
00000044 winedbg.exe
	00000045    0
00000041 (D) C:\users\robert\Minecraft Note Block Studio\Minecraft Note Block Studio.exe
	00000035    0
	00000043    0 <==
System information:
    Wine build: wine-1.6.2
    Platform: i386 (WOW64)
    Host system: Linux
    Host version: 4.15.0-50-generic

**Comment by ShinkoNet** [comment]
Wine does not work on note block studio, so if you're booting from a linux distro or Mac it won't work. Maybe in the future we will get it working on those platforms natively...

**Comment by AlsoScratch** [comment]
Hope to see NBS be WINE compatible! 😀

**Comment by AlsoScratch** [comment]
Is NBS fully 64 bit? If not, I can understand why it does not work.
