### ISSUE TITLE
Website: Nav panel toggle covers complete page

### ISSUE THREAD

**Issue by Marcono1234** [HielkeMinecraft/OpenNoteBlockStudio#95]
**Describe the bug**
On the website (https://hielkeminecraft.github.io/OpenNoteBlockStudio), if the window is not wide enough the navigation menu is shown on the left and can be toggled (see screenshot).
The problem is that the clickable area for the toggle action covers the complete screen (absolute, doesn't move when scrolling). This prevents the user from clicking any other links, such as the download link.

**To Reproduce**
1. Open https://hielkeminecraft.github.io/OpenNoteBlockStudio
2. Resize the window until the nav button in the top left appears (see screenshot)
3. Make sure you are at the top of the tab and have not scrolled down
4. Try clicking anywhere, including on the download buttons
:x: The navigation menu opens

**Expected behavior**
Only the navigation button should be clickable, not the complete / or parts of the page.

**Screenshots**
![Nav toggle button](https://user-images.githubusercontent.com/11685886/67162987-17a0ae00-f36a-11e9-85be-7d32e71847d8.png)

**Comment by grandmoffgigi** [comment]
I did this and it happened.

**Comment by Bentroen** [comment]
Fixed in 79568262f15e16c56e259a908798d6cac2669b6e.
