### ISSUE TITLE
Not seeing the export?

### ISSUE THREAD

**Issue by MonstyrSlayr** [HielkeMinecraft/OpenNoteBlockStudio#99]
**Describe the bug**
When I try to export a compatible project as a Minecraft Schematic (or mp3), I cannot locate any of my folders, and when I make a new folder for the schematic file (or mp3 file), I cannot locate it in File Explorer. Even if I do not make a folder, I cannot find the file.

**To Reproduce**
1. Export any project as any file in any location
2. Be unable to find the file or created folder

**Expected behavior**
See all of my folders when I export the file, and be able to locate the file when it is need.

**Screenshots**
![Actual File Explorer](https://user-images.githubusercontent.com/59293011/71529355-48ddb300-28b2-11ea-9564-af2509b7c410.png)
![MNBS File Explorer](https://user-images.githubusercontent.com/59293011/71529356-49764980-28b2-11ea-9963-745a074983ef.png)

**Additional context**
If it helps, I have an 8th gen Intel core on a Windows 10 HP Laptop.

**Comment by Bentroen** [comment]
Inconclusive report. Seems like something is going on with your system – doesn't seem to be related to the program, so I'm closing it for now. Feel free to leave a comment in case you want to add more information.
